### PR TITLE
Fixed bug brough by commit 43442d0690223a2c83e1e2380d94203a9ec52ddc

### PR DESCRIPTION
**Pull request by jojo59516**
I commented related codes and the bug [here](https://github.com/pschraut/UnityHeapExplorer/commit/43442d0690223a2c83e1e2380d94203a9ec52ddc#r49448887).

### CODE REVIEW

**Comment by jojo59516** [comment]
Oops, PR's title does not support link of commit.
Related commit is 43442d0690223a2c83e1e2380d94203a9ec52ddc. It is a fixture for issue #4.

**Comment by pschraut** [comment]
Thank you for the PR, excellent fix! I'm a bit short on time right now. I will review and merge your changes at the weekend.

**Comment by jojo59516** [comment]
Sure.
I'm developing a reference tree view based on this UnityHeapExplorer, for my own usage. So there would be more PRs and issues. Hope you don't mind :)
Thank you for this excellent tool again!

**Comment by pschraut** [comment]
Sure, no problem. Keep it coming!

**Comment by pschraut** [comment]
Thanks again for your contribution! I believe the search is also faster than the version I implemented earlier. So overall a really nice improvement!

**Pull request merged**
