### PR TITLE
Performance Optimization

### PR DESCRIPTION
**Pull request by jojo59516**
Hi Peter,
I found CPU utilization grows to 40%+ on my PC when `HeapExplorerWindow` opened. And it is mainly caused by [this line](https://github.com/pschraut/UnityHeapExplorer/blob/64c91ecd30ef03d4e928e3b66fd4361870f54a82/Editor/Scripts/HeapExplorerWindow.cs#L322): it makes the window repaints every event received but no matter what event it is. It caused to several repainting in one frame. I try to fix it in first commit: repaints only if received repaint event. It makes the CPU utilization decreases to <4%.
Secondly, I noticed the synchronization between threads violates the [best practice](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-best-practices#general-recommendations): aborting from main thread instead of notifying the thread to exit by itself and sleeping in while to reduce CPU utilization instead of using `Monitor.Wait()` to block itself and waiting for being awaken.
I have tested for several days. I have to say that, however, I am not an expert at either of above two points. There may be better implementation of them.

### CODE REVIEW

**Comment by jojo59516** [comment]
Oh god, forgive me for the poor English ;)

**Comment by pschraut** [comment]
Hi and once again thank you for the PR! 

Quick questions:

1. I added the repaint to make sure the window is updated while it displays the progress when analyzing a memory snapshot. Does this still work?

2. I added the Thread.Abort to allow closing Heap Explorer while "Analyzing snapshot" is in progress. Does this properly work with your changes? 

I'm going to take a look, test and merge it most likely over the weekend. Maybe even earlier when I find the time, but no promise.

**Comment by jojo59516** [comment]
Hi and thanks for the reply!
1. Yes, I got your point and made sure it does still work. (I have tested several views, including Welcome view, Managed Objects view, Native Objects view etc., but not all, due to the lack of familiarity to this tool.)
2. No. After this change, the action "closing Heap Explorer" will be completed once the current running job done, but NOT immediately like before. For me it is reasonable, but of course, it all depend on you. After all, the first commit has almost solved the high CPU utilization problem :)
Furthermore, we can make `m_Closing` public, then each job could check it to decide whether to continue.

**Comment by pschraut** [comment]
OK, I understand. If it's a long running job, it can be from advantage that the job checks if it should abort itself to avoid that we can close the window kind of immediately. It's OK when there is an one second delay or so, but the tool shouldn't wait like 10 minutes fora huge job to complete :)

**Comment by jojo59516** [comment]
I see. You are worry about a long-time freeze. This is a reasonable concern.
Then we can change `m_Thread.Join()` to `m_Thread.Join(maxWaitingTime)`, where `maxWaitingTime` is a constant integer indicates the limitation of freeze time.
But if it returns due to timeout instead of quitting thread, we still must call `Abort()` on `m_Thread`, what is [not recommended](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=net-5.0).
The completed solution may be that we require jobs always check the `m_Closing` or the their states in their for loops, in order to terminate in time.

**Comment by pschraut** [comment]
Yes, jobs should always check "m_Closing" in their loops. It believe jobs already update a progress variable every few milliseconds, we could use this to check for closing too. So that the closing check isn't performed each iteration, but in specific intervals. Not sure if it makes a performance difference though.

**Comment by jojo59516** [comment]
I believe it makes almost no performance difference.
I will do these changes these days, probably before this weekend, but no promise :P

**Comment by jojo59516** [comment]
Hi Peter
I have a problem of making above changes:
Ideally, I should refactor class `AbstractThreadJob` like
```C#
    public abstract class AbstractThreadJob
    {
        public enum State
        {
            Stopped,
            Queued,
            Running,
            Completed
        };

        public State state = State.Stopped;

        // To implement a heavy job, you should override this method and do things step by step here.
        protected virtual IEnumerator StepFunc()
        {
            yield break;
        }

        // To implement a lightweight job, you could override this method and do everything directly here.
        public virtual void ThreadFunc()
        {
            var enumerator = StepFunc();
            while (enumerator.MoveNext())
            {
                if (state == State.Stopped)
                    return; // Exiting
            }
        }

        public virtual void IntegrateFunc()
        {

        }
    }
```
and set job's `state` to `Stopped` in window's `OnDisable`:
```C#
        void OnDisable()
        {
            lock (m_ThreadJobs)
            {
                // ask thread to exit
                m_IsClosing = true;
                foreach (var job in m_ThreadJobs)
                {
                    job.state = AbstractThreadJob.State.Stopped;
                }
                Monitor.Pulse(m_ThreadJobs);
            }
            m_Thread.Join(); // wait for thread exit
            m_Thread = null;

            DestroyViews();
        }
```
and expect derived classes to override `StepThreadFunc`, in order to make a chance to detect the window is closing.
Unfortunately, most job's `ThreadFunc` cannot easily refactor to this form.

On the other hand, if I check `m_IsClosing` in job's method, I would face the problem of synchronization between threads and the problem of accessing of the instance of window. Also, I think it is not a good implementation yet, which is the most important.

**Comment by pschraut** [comment]
Hi, you're right, that seems like a lot of code needs to be changed.

My approach would be to have a static property `isClosing` somewhere, for example in [HeapExplorerWindow](https://github.com/pschraut/UnityHeapExplorer/blob/master/Editor/Scripts/HeapExplorerWindow.cs).

Only `HeapExplorerWindow` actually writes to `isClosing`. Code that runs on another thread, that's mostly the `BuildTree` methods, need to check if `HeapExplorerWindow.isClosing` evaluates to true. I think this shouldn't cause a synchronization issue.

Adding the following code at the beginning of [this loop](https://github.com/pschraut/UnityHeapExplorer/blob/master/Editor/Scripts/NativeObjectsView/NativeObjectsControl.cs#L172) would then allow to "stop" the code within one loop iteration:
```CSharp
if (HeapExplorerWindow.isClosing)
    break;
```

It might not be the ideal software design solution you find in books, but I think it gets the job done and seems to be easier to understand/implement than extending the `Job` themself.

**Comment by jojo59516** [comment]
Alright, I've fixed this issue mentioned above:
1. rename `HeapExplorerWindow.m_IsClosing` to `HeapExplorerWindow.isClosing`, and convert it to a property with public get and private set;
2. In `HeapExplorerWindow.OnDisable`, also set `m_Heap.abortActiveStepRequested` to false to abort the current crawling if needed;
3. In most job's `ThreadFunc`, check `HeapExplorerWindow.isClosing` the determine whether to continue or not.

**Comment by pschraut** [comment]
I made a few changes and merged your PR. Your first commit caused that the UI didn't update while a snapshot is being analyzed when no mouse/keyboard interaction was taking place.

So I changed the OnInspectorUpdate to the EditorApplication.update callback again, but added functionality to update the GUI in 50ms intervals only.

Thank you again for the contribution! 👍

**Comment by jojo59516** [comment]
You're welcome and great fix.
Thanks for the great tool again! :)

**Pull request merged**
